# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-20 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardItem',
            new_name='CartItem',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='card_key',
            new_name='cart_key',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set([('cart_key', 'product')]),
        ),
    ]
