# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-01 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160924_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Identificador'),
        ),
    ]
